language: php
php:
  - '5.6'
before_script: composer update
script: phpunit --testsuite Tests --configuration Tests/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f6151f46-6562-46c0-8582-37ef78fad3dc
